language: node_js
node_js:
  - 4.5.0
before_script:
- chmod +x ./cibuild.sh
- ssh-keyscan -H -t rsa,dsa $hostname >> ~/.ssh/known_hosts
script: "./cibuild.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CXX=g++-4.8
sudo: false
addons:
  ssh_known_hosts: $hostname
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_4395499fa958_key -iv $encrypted_4395499fa958_iv
  -in dash.org-test-web.pem.enc -out dash.org-test-web.pem -d
- rvm install 2.3.1
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/$IdentityFile
- ssh-add $TRAVIS_BUILD_DIR/$IdentityFile
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -c -v --delete-after --exclude-from 'ciexclude.txt' $TRAVIS_BUILD_DIR/_site/ $user@$hostname:$production_path
  on:
    branch: master
