markdown: kramdown
exclude:
  - README.md
  - rss.xml
  - _posts/README.md
  - assets/mockups/
paginate: 5
paginate_path: "/blog/page:num/"
name: Dash
url: https://www.dash.org
description: Digital Cash

api: http://www-test.dash.org/api/v1

languages: ["en", "es", "cn", "pt", "ru", "it"]
exclude_from_localizations: ["assets"]

sass:
  style: compressed
  cache: false

autoprefixer:
  browsers:
    - last 2 versions

gems:
  - jekyll-paginate
  - jekyll-autoprefixer
  - jekyll-multiple-languages-plugin

collections:
  components: # style guide
    output: false
  colors: # style guide
    output: false
