markdown: kramdown
exclude:
  - README.md
  - rss.xml
  - _posts/README.md
  - assets/mockups/
  - vendor/
  - script/
  - src/
  - dist/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
paginate: 5
paginate_path: "/blog/page:num/"
name: Dash
url: https://www.dash.org
description: Digital Cash

api: http://www-test.dash.org/api/v1

languages: ["en", "es", "cn", "pt", "ru", "it"]
exclude_from_localizations: ["assets","dist","style-guide"]

gems:
  - jekyll-paginate
  - jekyll-multiple-languages-plugin

collections:
  components: # style guide
    output: false
  colors: # style guide
    output: false
