markdown: kramdown
exclude:
  - README.md
  - rss.xml
  - ciexclude.txt
  - _posts/README.md
  - assets/mockups/
  - vendor/
  - script/
  - src/
  - dist/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
paginate: 12
paginate_path: "/blog/page:num/"
name: Dash
url: https://www.dash.org
description: Digital Cash

url: https://www.dash.org

api: /api/v1

#languages: ["en", "es", "cn", "pt", "ru", "it"]
languages: ["en","es", "cn", "ru", "pt", "fr", "jp"]
exclude_from_localizations: ["assets","dist","style-guide"]

plugins:
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - jekyll-srcset-tag

collections:
  components: # style guide
    output: false
  colors: # style guide
    output: false

# https://github.com/kinnetica/jekyll-plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
    - "/style-guide/index.html"
    - "/rss/dash_blog_rss.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

srcset:
  source: assets/img
  output: assets/img/resized

keep_files: ['assets/img/resized','fr/assets/img/resized','es/assets/img/resized','cn/assets/img/resized','pt/assets/img/resized','ru/assets/img/resized','it/assets/img/resized']
